# vim: noai:ts=2:sw=2:ft=yaml:
language: minimal

git:
  depth: 1

sudo: required

services:
  - docker

env:
  global:
    - secure: "GI2Wlc2VDWgPJ74N0W15G5F46qy9mv67YND4+TkYEz0FRJid5xTHwgYjwEkup2it4BDJo7F4p+RFicQR2DXQb6KIC/ZIPZOWW7c2f/42j0l4R5A16DoPZRil6bfZTwfUsQJi+Mnhd46KrjHvJHmz2kK+U3VXhcKJnpqqMFKngPHI0teJp5Tg0d21O4oLUp9WhxhdcocfCzVcE+Bt8KpVsfW5nlL5HQv+jOb2vYjRWUC8TAGuG5fPiW0TsUZZmAaG5H+o/dE69gv4GjMqGEbyEgH0l64g45Z1NOBfmdRnXaJPOZuixUKX4VWn6sShIgk2q1TCWVgfDCBTaufvJqc9y3g5NDUoAnqlK+tvuIJLKXUXOZtcPwAhupFKga7DIpanyssUKdS7XUkbZGd+Yq6Fh8/bPoY2qdNwm6/NXSt1xA2i5rwq+ikmlgqyXCWAualAOiljNMOFEO9XohY9EAKSzxVDZVGhZOuzbGbnCZRpzYHJJAKfn92qoxjFwv3wTAnq9IIBHrLk3JKsBF1P8fvShe8HYZYkfPsTsFz3E0DVbWp65GZR218LNPUidLSey0z02YfcODklVQ4T1eRQIxumqpjeGTEYOFQ3aBFP0x3lajd0JiuRBAQqjjWYZWlG3JxBQL+Cvow/fjyF2/pNfogVLKnc3fshT5yhIGEANa4RQzM="

# setup dependencies required for testing
before_install:
  - docker pull centos:8

# execute unit testing and code coverage
install:
  - docker run -eCOVERALLS_TOKEN -uroot --network host -it --volume $PWD:/go/src/github.com/infrawatch/sg-core:z --workdir /go/src/github.com/infrawatch/sg-core centos:8 /bin/sh -c 'sh ./build/test-framework/run_tests.sh'

# functional testing (validate it works)
script:
  - docker build --tag infrawatch/sg-core:latest .
  - docker images
