---
sources:
    - name: meter_source
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      publishers:
          - notifier://127.0.0.1:5666/?driver=amqp&topic=metering
