name: CI
env:
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-framework:
    name: Base testing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit testing and code coverage
        run: |
          docker run -eCOVERALLS_TOKEN -uroot --network host -i --volume $GITHUB_WORKSPACE:/go/src/github.com/infrawatch/sg-core:z --workdir /go/src/github.com/infrawatch/sg-core registry.access.redhat.com/ubi8 /bin/sh -c 'sh ./build/test-framework/run_tests.sh'

      - name: Verify image builds
        run: |
          docker build --tag infrawatch/sg-core:latest --file build/Dockerfile .

      - name: List images
        run: |
          docker images
