name: CI
env:
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
on: push

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.33

  test-framework:
    name: Base testing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit testing and code coverage
        run: |
          docker run -eCOVERALLS_TOKEN -uroot --network host -i --volume $GITHUB_WORKSPACE:/go/src/github.com/infrawatch/sg-core:z --workdir /go/src/github.com/infrawatch/sg-core registry.access.redhat.com/ubi8 /bin/sh -c 'sh ./build/test-framework/run_tests.sh'

      - name: Verify image builds
        run: |
          docker build --tag infrawatch/sg-core:latest --file build/Dockerfile .

      - name: List images
        run: |
          docker images
